name: AI Database Healer

on:
  workflow_dispatch: # Manual button se chalane ke liye

jobs:
  run-ai-healer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install firebase-admin google-generativeai requests pypdf google-cloud-firestore google-api-core --upgrade

      - name: Setup Firebase Key
        run: |
          cat << 'EOF' > serviceAccountKey.json
          ${{ secrets.FIREBASE_JSON_DATA }}
          EOF

      - name: Run AI Extractor
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python 1_extract_and_fix.py
